config/routes.rb
Rails.application.routes.draw do
  resources :trades

  resources :sectors

  resources :order_books

  resources :market_summaries

  resources :market_statuses

  resources :issuers

  resources :instruments

  resources :indices

  resources :boards

  resources :announcements

end

app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  id          :integer          not null, primary key
#  MSG_NAME    :string(255)
#  MESSAGE     :string(255)
#  SUBJECT     :string(255)
#  SendingTime :datetime
#  created_at  :datetime
#  updated_at  :datetime
#

class Announcement < ActiveRecord::Base
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:MSG_NAME, :MESSAGE, :SUBJECT, :SendingTime)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :MSG_NAME %><br>
    <%= f.text_field :MSG_NAME %>
  </div>
  <div class="field">
    <%= f.label :MESSAGE %><br>
    <%= f.text_field :MESSAGE %>
  </div>
  <div class="field">
    <%= f.label :SUBJECT %><br>
    <%= f.text_field :SUBJECT %>
  </div>
  <div class="field">
    <%= f.label :SendingTime %><br>
    <%= f.datetime_select :SendingTime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <thead>
    <tr>
      <th>Msg name</th>
      <th>Message</th>
      <th>Subject</th>
      <th>Sendingtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.MSG_NAME %></td>
        <td><%= announcement.MESSAGE %></td>
        <td><%= announcement.SUBJECT %></td>
        <td><%= announcement.SendingTime %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Msg name:</strong>
  <%= @announcement.MSG_NAME %>
</p>

<p>
  <strong>Message:</strong>
  <%= @announcement.MESSAGE %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @announcement.SUBJECT %>
</p>

<p>
  <strong>Sendingtime:</strong>
  <%= @announcement.SendingTime %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>