config/routes.rb
Rails.application.routes.draw do
  resources :trades

  resources :sectors

  resources :order_books

  resources :market_summaries

  resources :market_statuses

  resources :issuers

  resources :instruments

  resources :indices

  resources :boards

  resources :announcements

end

app/models/issuer.rb
# == Schema Information
#
# Table name: issuers
#
#  id          :integer          not null, primary key
#  ISSUER_ID   :string(255)
#  SendingTime :datetime
#  created_at  :datetime
#  updated_at  :datetime
#

class Issuer < ActiveRecord::Base
end

app/controllers/issuers_controller.rb
class IssuersController < ApplicationController
  before_action :set_issuer, only: [:show, :edit, :update, :destroy]

  # GET /issuers
  # GET /issuers.json
  def index
    @issuers = Issuer.all
  end

  # GET /issuers/1
  # GET /issuers/1.json
  def show
  end

  # GET /issuers/new
  def new
    @issuer = Issuer.new
  end

  # GET /issuers/1/edit
  def edit
  end

  # POST /issuers
  # POST /issuers.json
  def create
    @issuer = Issuer.new(issuer_params)

    respond_to do |format|
      if @issuer.save
        format.html { redirect_to @issuer, notice: 'Issuer was successfully created.' }
        format.json { render :show, status: :created, location: @issuer }
      else
        format.html { render :new }
        format.json { render json: @issuer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issuers/1
  # PATCH/PUT /issuers/1.json
  def update
    respond_to do |format|
      if @issuer.update(issuer_params)
        format.html { redirect_to @issuer, notice: 'Issuer was successfully updated.' }
        format.json { render :show, status: :ok, location: @issuer }
      else
        format.html { render :edit }
        format.json { render json: @issuer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issuers/1
  # DELETE /issuers/1.json
  def destroy
    @issuer.destroy
    respond_to do |format|
      format.html { redirect_to issuers_url, notice: 'Issuer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issuer
      @issuer = Issuer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issuer_params
      params.require(:issuer).permit(:ISSUER_ID, :SendingTime)
    end
end

app/helpers/issuers_helper.rb
module IssuersHelper
end

app/views/issuers/_form.html.erb
<%= form_for(@issuer) do |f| %>
  <% if @issuer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issuer.errors.count, "error") %> prohibited this issuer from being saved:</h2>

      <ul>
      <% @issuer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ISSUER_ID %><br>
    <%= f.text_field :ISSUER_ID %>
  </div>
  <div class="field">
    <%= f.label :SendingTime %><br>
    <%= f.datetime_select :SendingTime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issuers/edit.html.erb
<h1>Editing issuer</h1>

<%= render 'form' %>

<%= link_to 'Show', @issuer %> |
<%= link_to 'Back', issuers_path %>

app/views/issuers/index.html.erb
<h1>Listing issuers</h1>

<table>
  <thead>
    <tr>
      <th>Issuer id</th>
      <th>Sendingtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issuers.each do |issuer| %>
      <tr>
        <td><%= issuer.ISSUER_ID %></td>
        <td><%= issuer.SendingTime %></td>
        <td><%= link_to 'Show', issuer %></td>
        <td><%= link_to 'Edit', edit_issuer_path(issuer) %></td>
        <td><%= link_to 'Destroy', issuer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issuer', new_issuer_path %>

app/views/issuers/new.html.erb
<h1>New issuer</h1>

<%= render 'form' %>

<%= link_to 'Back', issuers_path %>

app/views/issuers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issuer id:</strong>
  <%= @issuer.ISSUER_ID %>
</p>

<p>
  <strong>Sendingtime:</strong>
  <%= @issuer.SendingTime %>
</p>

<%= link_to 'Edit', edit_issuer_path(@issuer) %> |
<%= link_to 'Back', issuers_path %>