config/routes.rb
Rails.application.routes.draw do
  resources :trades

  resources :sectors

  resources :order_books

  resources :market_summaries

  resources :market_statuses

  resources :issuers

  resources :instruments

  resources :indices

  resources :boards

  resources :announcements

end

app/controllers/market_statuses_controller.rb
class MarketStatusesController < ApplicationController
  before_action :set_market_status, only: [:show, :edit, :update, :destroy]

  # GET /market_statuses
  # GET /market_statuses.json
  def index
    @market_statuses = MarketStatus.all
  end

  # GET /market_statuses/1
  # GET /market_statuses/1.json
  def show
  end

  # GET /market_statuses/new
  def new
    @market_status = MarketStatus.new
  end

  # GET /market_statuses/1/edit
  def edit
  end

  # POST /market_statuses
  # POST /market_statuses.json
  def create
    @market_status = MarketStatus.new(market_status_params)

    respond_to do |format|
      if @market_status.save
        format.html { redirect_to @market_status, notice: 'Market status was successfully created.' }
        format.json { render :show, status: :created, location: @market_status }
      else
        format.html { render :new }
        format.json { render json: @market_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /market_statuses/1
  # PATCH/PUT /market_statuses/1.json
  def update
    respond_to do |format|
      if @market_status.update(market_status_params)
        format.html { redirect_to @market_status, notice: 'Market status was successfully updated.' }
        format.json { render :show, status: :ok, location: @market_status }
      else
        format.html { render :edit }
        format.json { render json: @market_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /market_statuses/1
  # DELETE /market_statuses/1.json
  def destroy
    @market_status.destroy
    respond_to do |format|
      format.html { redirect_to market_statuses_url, notice: 'Market status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market_status
      @market_status = MarketStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_status_params
      params.require(:market_status).permit(:STATUS, :SendingTime)
    end
end

app/helpers/market_statuses_helper.rb
module MarketStatusesHelper
end

app/views/market_statuses/_form.html.erb
<%= form_for(@market_status) do |f| %>
  <% if @market_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market_status.errors.count, "error") %> prohibited this market_status from being saved:</h2>

      <ul>
      <% @market_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :STATUS %><br>
    <%= f.text_field :STATUS %>
  </div>
  <div class="field">
    <%= f.label :SendingTime %><br>
    <%= f.datetime_select :SendingTime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/market_statuses/edit.html.erb
<h1>Editing market_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @market_status %> |
<%= link_to 'Back', market_statuses_path %>

app/views/market_statuses/index.html.erb
<h1>Listing market_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Sendingtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @market_statuses.each do |market_status| %>
      <tr>
        <td><%= market_status.STATUS %></td>
        <td><%= market_status.SendingTime %></td>
        <td><%= link_to 'Show', market_status %></td>
        <td><%= link_to 'Edit', edit_market_status_path(market_status) %></td>
        <td><%= link_to 'Destroy', market_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Market status', new_market_status_path %>

app/views/market_statuses/new.html.erb
<h1>New market_status</h1>

<%= render 'form' %>

<%= link_to 'Back', market_statuses_path %>

app/views/market_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @market_status.STATUS %>
</p>

<p>
  <strong>Sendingtime:</strong>
  <%= @market_status.SendingTime %>
</p>

<%= link_to 'Edit', edit_market_status_path(@market_status) %> |
<%= link_to 'Back', market_statuses_path %>