config/routes.rb
Rails.application.routes.draw do
  resources :trades

  resources :sectors

  resources :order_books

  resources :market_summaries

  resources :market_statuses

  resources :issuers

  resources :instruments

  resources :indices

  resources :boards

  resources :announcements

end

app/models/instrument.rb
# == Schema Information
#
# Table name: instruments
#
#  id                 :integer          not null, primary key
#  SecurityID         :string(255)
#  IssueDate          :date
#  ISIN               :string(255)
#  QUANTITY_ISSUED    :integer
#  PAR_VALUE          :float
#  ISSUED_PRICE       :float
#  LAST_TRADED_PRICE  :float
#  WTD_HI_PRICE       :float
#  MTD_HI_PRICE       :float
#  YTD_HI_PRICE       :float
#  P12_HI_PRICE       :float
#  ALL_HI_PRICE       :float
#  ALL_LO_PRICE       :float
#  WTD_LO_PRICE       :float
#  MTD_LO_PRICE       :float
#  YTD_LO_PRICE       :float
#  P12_LO_PRICE       :float
#  TDY_SHARE_VOL      :integer
#  WTD_SHARE_VOL      :integer
#  MTD_SHARE_VOL      :integer
#  YTD_SHARE_VOL      :integer
#  P12_SHARE_VOL      :integer
#  TDY_TRADE_VOL      :integer
#  WTD_TRADE_VOL      :integer
#  MTD_TRADE_VOL      :integer
#  YTD_TRADE_VOL      :integer
#  P12_TRADE_VOL      :integer
#  TDY_TURNOVER       :float
#  WTD_TURNOVER       :float
#  MTD_TURNOVER       :float
#  YTD_TURNOVER       :float
#  P12_TURNOVER       :float
#  PREVIOUS_CLOSE     :float
#  FOREIGN_HOLDINGS   :float
#  XC                 :integer
#  XD                 :integer
#  XR                 :integer
#  FOREIGN_PERCENTAGE :float
#  DATE               :date
#  HI_TRADE           :integer
#  LO_TRADE           :integer
#  CLOSING_PRICE      :float
#  SendingTime        :datetime
#  created_at         :datetime
#  updated_at         :datetime
#

class Instrument < ActiveRecord::Base
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:SecurityID, :IssueDate, :ISIN, :QUANTITY_ISSUED, :PAR_VALUE, :ISSUED_PRICE, :LAST_TRADED_PRICE, :WTD_HI_PRICE, :MTD_HI_PRICE, :YTD_HI_PRICE, :P12_HI_PRICE, :ALL_HI_PRICE, :ALL_LO_PRICE, :WTD_LO_PRICE, :MTD_LO_PRICE, :YTD_LO_PRICE, :P12_LO_PRICE, :TDY_SHARE_VOL, :WTD_SHARE_VOL, :MTD_SHARE_VOL, :YTD_SHARE_VOL, :P12_SHARE_VOL, :TDY_TRADE_VOL, :WTD_TRADE_VOL, :MTD_TRADE_VOL, :YTD_TRADE_VOL, :P12_TRADE_VOL, :TDY_TURNOVER, :WTD_TURNOVER, :MTD_TURNOVER, :YTD_TURNOVER, :P12_TURNOVER, :PREVIOUS_CLOSE, :FOREIGN_HOLDINGS, :XC, :XD, :XR, :FOREIGN_PERCENTAGE, :DATE, :HI_TRADE, :LO_TRADE, :CLOSING_PRICE, :SendingTime)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.erb
<%= form_for(@instrument) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :SecurityID %><br>
    <%= f.text_field :SecurityID %>
  </div>
  <div class="field">
    <%= f.label :IssueDate %><br>
    <%= f.date_select :IssueDate %>
  </div>
  <div class="field">
    <%= f.label :ISIN %><br>
    <%= f.text_field :ISIN %>
  </div>
  <div class="field">
    <%= f.label :QUANTITY_ISSUED %><br>
    <%= f.number_field :QUANTITY_ISSUED %>
  </div>
  <div class="field">
    <%= f.label :PAR_VALUE %><br>
    <%= f.text_field :PAR_VALUE %>
  </div>
  <div class="field">
    <%= f.label :ISSUED_PRICE %><br>
    <%= f.text_field :ISSUED_PRICE %>
  </div>
  <div class="field">
    <%= f.label :LAST_TRADED_PRICE %><br>
    <%= f.text_field :LAST_TRADED_PRICE %>
  </div>
  <div class="field">
    <%= f.label :WTD_HI_PRICE %><br>
    <%= f.text_field :WTD_HI_PRICE %>
  </div>
  <div class="field">
    <%= f.label :MTD_HI_PRICE %><br>
    <%= f.text_field :MTD_HI_PRICE %>
  </div>
  <div class="field">
    <%= f.label :YTD_HI_PRICE %><br>
    <%= f.text_field :YTD_HI_PRICE %>
  </div>
  <div class="field">
    <%= f.label :P12_HI_PRICE %><br>
    <%= f.text_field :P12_HI_PRICE %>
  </div>
  <div class="field">
    <%= f.label :ALL_HI_PRICE %><br>
    <%= f.text_field :ALL_HI_PRICE %>
  </div>
  <div class="field">
    <%= f.label :ALL_LO_PRICE %><br>
    <%= f.text_field :ALL_LO_PRICE %>
  </div>
  <div class="field">
    <%= f.label :WTD_LO_PRICE %><br>
    <%= f.text_field :WTD_LO_PRICE %>
  </div>
  <div class="field">
    <%= f.label :MTD_LO_PRICE %><br>
    <%= f.text_field :MTD_LO_PRICE %>
  </div>
  <div class="field">
    <%= f.label :YTD_LO_PRICE %><br>
    <%= f.text_field :YTD_LO_PRICE %>
  </div>
  <div class="field">
    <%= f.label :P12_LO_PRICE %><br>
    <%= f.text_field :P12_LO_PRICE %>
  </div>
  <div class="field">
    <%= f.label :TDY_SHARE_VOL %><br>
    <%= f.number_field :TDY_SHARE_VOL %>
  </div>
  <div class="field">
    <%= f.label :WTD_SHARE_VOL %><br>
    <%= f.number_field :WTD_SHARE_VOL %>
  </div>
  <div class="field">
    <%= f.label :MTD_SHARE_VOL %><br>
    <%= f.number_field :MTD_SHARE_VOL %>
  </div>
  <div class="field">
    <%= f.label :YTD_SHARE_VOL %><br>
    <%= f.number_field :YTD_SHARE_VOL %>
  </div>
  <div class="field">
    <%= f.label :P12_SHARE_VOL %><br>
    <%= f.number_field :P12_SHARE_VOL %>
  </div>
  <div class="field">
    <%= f.label :TDY_TRADE_VOL %><br>
    <%= f.number_field :TDY_TRADE_VOL %>
  </div>
  <div class="field">
    <%= f.label :WTD_TRADE_VOL %><br>
    <%= f.number_field :WTD_TRADE_VOL %>
  </div>
  <div class="field">
    <%= f.label :MTD_TRADE_VOL %><br>
    <%= f.number_field :MTD_TRADE_VOL %>
  </div>
  <div class="field">
    <%= f.label :YTD_TRADE_VOL %><br>
    <%= f.number_field :YTD_TRADE_VOL %>
  </div>
  <div class="field">
    <%= f.label :P12_TRADE_VOL %><br>
    <%= f.number_field :P12_TRADE_VOL %>
  </div>
  <div class="field">
    <%= f.label :TDY_TURNOVER %><br>
    <%= f.text_field :TDY_TURNOVER %>
  </div>
  <div class="field">
    <%= f.label :WTD_TURNOVER %><br>
    <%= f.text_field :WTD_TURNOVER %>
  </div>
  <div class="field">
    <%= f.label :MTD_TURNOVER %><br>
    <%= f.text_field :MTD_TURNOVER %>
  </div>
  <div class="field">
    <%= f.label :YTD_TURNOVER %><br>
    <%= f.text_field :YTD_TURNOVER %>
  </div>
  <div class="field">
    <%= f.label :P12_TURNOVER %><br>
    <%= f.text_field :P12_TURNOVER %>
  </div>
  <div class="field">
    <%= f.label :PREVIOUS_CLOSE %><br>
    <%= f.text_field :PREVIOUS_CLOSE %>
  </div>
  <div class="field">
    <%= f.label :FOREIGN_HOLDINGS %><br>
    <%= f.text_field :FOREIGN_HOLDINGS %>
  </div>
  <div class="field">
    <%= f.label :XC %><br>
    <%= f.number_field :XC %>
  </div>
  <div class="field">
    <%= f.label :XD %><br>
    <%= f.number_field :XD %>
  </div>
  <div class="field">
    <%= f.label :XR %><br>
    <%= f.number_field :XR %>
  </div>
  <div class="field">
    <%= f.label :FOREIGN_PERCENTAGE %><br>
    <%= f.text_field :FOREIGN_PERCENTAGE %>
  </div>
  <div class="field">
    <%= f.label :DATE %><br>
    <%= f.date_select :DATE %>
  </div>
  <div class="field">
    <%= f.label :HI_TRADE %><br>
    <%= f.number_field :HI_TRADE %>
  </div>
  <div class="field">
    <%= f.label :LO_TRADE %><br>
    <%= f.number_field :LO_TRADE %>
  </div>
  <div class="field">
    <%= f.label :CLOSING_PRICE %><br>
    <%= f.text_field :CLOSING_PRICE %>
  </div>
  <div class="field">
    <%= f.label :SendingTime %><br>
    <%= f.datetime_select :SendingTime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<h1>Listing instruments</h1>

<table>
  <thead>
    <tr>
      <th>Securityid</th>
      <th>Issuedate</th>
      <th>Isin</th>
      <th>Quantity issued</th>
      <th>Par value</th>
      <th>Issued price</th>
      <th>Last traded price</th>
      <th>Wtd hi price</th>
      <th>Mtd hi price</th>
      <th>Ytd hi price</th>
      <th>P12 hi price</th>
      <th>All hi price</th>
      <th>All lo price</th>
      <th>Wtd lo price</th>
      <th>Mtd lo price</th>
      <th>Ytd lo price</th>
      <th>P12 lo price</th>
      <th>Tdy share vol</th>
      <th>Wtd share vol</th>
      <th>Mtd share vol</th>
      <th>Ytd share vol</th>
      <th>P12 share vol</th>
      <th>Tdy trade vol</th>
      <th>Wtd trade vol</th>
      <th>Mtd trade vol</th>
      <th>Ytd trade vol</th>
      <th>P12 trade vol</th>
      <th>Tdy turnover</th>
      <th>Wtd turnover</th>
      <th>Mtd turnover</th>
      <th>Ytd turnover</th>
      <th>P12 turnover</th>
      <th>Previous close</th>
      <th>Foreign holdings</th>
      <th>Xc</th>
      <th>Xd</th>
      <th>Xr</th>
      <th>Foreign percentage</th>
      <th>Date</th>
      <th>Hi trade</th>
      <th>Lo trade</th>
      <th>Closing price</th>
      <th>Sendingtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instruments.each do |instrument| %>
      <tr>
        <td><%= instrument.SecurityID %></td>
        <td><%= instrument.IssueDate %></td>
        <td><%= instrument.ISIN %></td>
        <td><%= instrument.QUANTITY_ISSUED %></td>
        <td><%= instrument.PAR_VALUE %></td>
        <td><%= instrument.ISSUED_PRICE %></td>
        <td><%= instrument.LAST_TRADED_PRICE %></td>
        <td><%= instrument.WTD_HI_PRICE %></td>
        <td><%= instrument.MTD_HI_PRICE %></td>
        <td><%= instrument.YTD_HI_PRICE %></td>
        <td><%= instrument.P12_HI_PRICE %></td>
        <td><%= instrument.ALL_HI_PRICE %></td>
        <td><%= instrument.ALL_LO_PRICE %></td>
        <td><%= instrument.WTD_LO_PRICE %></td>
        <td><%= instrument.MTD_LO_PRICE %></td>
        <td><%= instrument.YTD_LO_PRICE %></td>
        <td><%= instrument.P12_LO_PRICE %></td>
        <td><%= instrument.TDY_SHARE_VOL %></td>
        <td><%= instrument.WTD_SHARE_VOL %></td>
        <td><%= instrument.MTD_SHARE_VOL %></td>
        <td><%= instrument.YTD_SHARE_VOL %></td>
        <td><%= instrument.P12_SHARE_VOL %></td>
        <td><%= instrument.TDY_TRADE_VOL %></td>
        <td><%= instrument.WTD_TRADE_VOL %></td>
        <td><%= instrument.MTD_TRADE_VOL %></td>
        <td><%= instrument.YTD_TRADE_VOL %></td>
        <td><%= instrument.P12_TRADE_VOL %></td>
        <td><%= instrument.TDY_TURNOVER %></td>
        <td><%= instrument.WTD_TURNOVER %></td>
        <td><%= instrument.MTD_TURNOVER %></td>
        <td><%= instrument.YTD_TURNOVER %></td>
        <td><%= instrument.P12_TURNOVER %></td>
        <td><%= instrument.PREVIOUS_CLOSE %></td>
        <td><%= instrument.FOREIGN_HOLDINGS %></td>
        <td><%= instrument.XC %></td>
        <td><%= instrument.XD %></td>
        <td><%= instrument.XR %></td>
        <td><%= instrument.FOREIGN_PERCENTAGE %></td>
        <td><%= instrument.DATE %></td>
        <td><%= instrument.HI_TRADE %></td>
        <td><%= instrument.LO_TRADE %></td>
        <td><%= instrument.CLOSING_PRICE %></td>
        <td><%= instrument.SendingTime %></td>
        <td><%= link_to 'Show', instrument %></td>
        <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
        <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instrument', new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Securityid:</strong>
  <%= @instrument.SecurityID %>
</p>

<p>
  <strong>Issuedate:</strong>
  <%= @instrument.IssueDate %>
</p>

<p>
  <strong>Isin:</strong>
  <%= @instrument.ISIN %>
</p>

<p>
  <strong>Quantity issued:</strong>
  <%= @instrument.QUANTITY_ISSUED %>
</p>

<p>
  <strong>Par value:</strong>
  <%= @instrument.PAR_VALUE %>
</p>

<p>
  <strong>Issued price:</strong>
  <%= @instrument.ISSUED_PRICE %>
</p>

<p>
  <strong>Last traded price:</strong>
  <%= @instrument.LAST_TRADED_PRICE %>
</p>

<p>
  <strong>Wtd hi price:</strong>
  <%= @instrument.WTD_HI_PRICE %>
</p>

<p>
  <strong>Mtd hi price:</strong>
  <%= @instrument.MTD_HI_PRICE %>
</p>

<p>
  <strong>Ytd hi price:</strong>
  <%= @instrument.YTD_HI_PRICE %>
</p>

<p>
  <strong>P12 hi price:</strong>
  <%= @instrument.P12_HI_PRICE %>
</p>

<p>
  <strong>All hi price:</strong>
  <%= @instrument.ALL_HI_PRICE %>
</p>

<p>
  <strong>All lo price:</strong>
  <%= @instrument.ALL_LO_PRICE %>
</p>

<p>
  <strong>Wtd lo price:</strong>
  <%= @instrument.WTD_LO_PRICE %>
</p>

<p>
  <strong>Mtd lo price:</strong>
  <%= @instrument.MTD_LO_PRICE %>
</p>

<p>
  <strong>Ytd lo price:</strong>
  <%= @instrument.YTD_LO_PRICE %>
</p>

<p>
  <strong>P12 lo price:</strong>
  <%= @instrument.P12_LO_PRICE %>
</p>

<p>
  <strong>Tdy share vol:</strong>
  <%= @instrument.TDY_SHARE_VOL %>
</p>

<p>
  <strong>Wtd share vol:</strong>
  <%= @instrument.WTD_SHARE_VOL %>
</p>

<p>
  <strong>Mtd share vol:</strong>
  <%= @instrument.MTD_SHARE_VOL %>
</p>

<p>
  <strong>Ytd share vol:</strong>
  <%= @instrument.YTD_SHARE_VOL %>
</p>

<p>
  <strong>P12 share vol:</strong>
  <%= @instrument.P12_SHARE_VOL %>
</p>

<p>
  <strong>Tdy trade vol:</strong>
  <%= @instrument.TDY_TRADE_VOL %>
</p>

<p>
  <strong>Wtd trade vol:</strong>
  <%= @instrument.WTD_TRADE_VOL %>
</p>

<p>
  <strong>Mtd trade vol:</strong>
  <%= @instrument.MTD_TRADE_VOL %>
</p>

<p>
  <strong>Ytd trade vol:</strong>
  <%= @instrument.YTD_TRADE_VOL %>
</p>

<p>
  <strong>P12 trade vol:</strong>
  <%= @instrument.P12_TRADE_VOL %>
</p>

<p>
  <strong>Tdy turnover:</strong>
  <%= @instrument.TDY_TURNOVER %>
</p>

<p>
  <strong>Wtd turnover:</strong>
  <%= @instrument.WTD_TURNOVER %>
</p>

<p>
  <strong>Mtd turnover:</strong>
  <%= @instrument.MTD_TURNOVER %>
</p>

<p>
  <strong>Ytd turnover:</strong>
  <%= @instrument.YTD_TURNOVER %>
</p>

<p>
  <strong>P12 turnover:</strong>
  <%= @instrument.P12_TURNOVER %>
</p>

<p>
  <strong>Previous close:</strong>
  <%= @instrument.PREVIOUS_CLOSE %>
</p>

<p>
  <strong>Foreign holdings:</strong>
  <%= @instrument.FOREIGN_HOLDINGS %>
</p>

<p>
  <strong>Xc:</strong>
  <%= @instrument.XC %>
</p>

<p>
  <strong>Xd:</strong>
  <%= @instrument.XD %>
</p>

<p>
  <strong>Xr:</strong>
  <%= @instrument.XR %>
</p>

<p>
  <strong>Foreign percentage:</strong>
  <%= @instrument.FOREIGN_PERCENTAGE %>
</p>

<p>
  <strong>Date:</strong>
  <%= @instrument.DATE %>
</p>

<p>
  <strong>Hi trade:</strong>
  <%= @instrument.HI_TRADE %>
</p>

<p>
  <strong>Lo trade:</strong>
  <%= @instrument.LO_TRADE %>
</p>

<p>
  <strong>Closing price:</strong>
  <%= @instrument.CLOSING_PRICE %>
</p>

<p>
  <strong>Sendingtime:</strong>
  <%= @instrument.SendingTime %>
</p>

<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<%= link_to 'Back', instruments_path %>